SeleniumTests/Alura.LeilaoOnline.WebApp/Models/DashboardInteressadaViewModel.cs
using Alura.LeilaoOnline.Core;
using System.Collections.Generic;

namespace Alura.LeilaoOnline.WebApp.Models
{
    public class DashboardInteressadaViewModel
    {
        public IEnumerable<Lance> MinhasOfertas { get; set; }
        public IEnumerable<Leilao> LeiloesFavoritos { get; set; }
    }
}

SeleniumTests/Alura.LeilaoOnline.WebApp/Models/Paginacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Alura.LeilaoOnline.WebApp.Models
{
    public class Paginacao
    {

    }

    public class Pagina
    {
        public int Atual { get; set; }
        public int Anterior { get; set; }
        public int Proxima { get; set; }
        public int TotalItens { get; set; }
    }

    public class Pagina<T>
    {
        public Pagina Info { get; set; }
        public IEnumerable<T> Items { get; set; }
    }
}

SeleniumTests/Alura.LeilaoOnline.WebApp/Controllers/AutenticacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Alura.LeilaoOnline.Core;
using Alura.LeilaoOnline.WebApp.Dados;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.WebApp.Extensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    public class AutenticacaoController : Controller
    {
        private readonly IRepositorio<Usuario> _repo;

        public AutenticacaoController(IRepositorio<Usuario> repositorio)
        {
            _repo = repositorio;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var usuario = _repo.Todos.First(u => u.Email == model.Login && u.Senha == model.Password);
                if (usuario != null)
                {
                    usuario = _repo.BuscarPorId(usuario.Id);
                    //autenticar
                    HttpContext.Session.Set<Usuario>("usuarioLogado", usuario);
                    return RedirectToAction("Index", "Interessadas");
                }
                ModelState.AddModelError("usuarioInvalido", "Usuário não encontrado");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("usuarioLogado");
            return RedirectToAction("Index", new { Controller = "Home" });
        }
    }
}

SeleniumTests/Alura.LeilaoOnline.WebApp/Controllers/InteressadasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Alura.LeilaoOnline.WebApp.Filtros;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.Core;
using Alura.LeilaoOnline.WebApp.Dados;
using Alura.LeilaoOnline.WebApp.Extensions;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    [AutorizacaoFilter]
    public class InteressadasController : Controller
    {

        private readonly IRepositorio<Leilao> _repoLeilao;
        private readonly IRepositorio<Interessada> _repoInteressada;

        public InteressadasController(
            IRepositorio<Leilao> repoLeilao, 
            IRepositorio<Interessada> repoInteressada)
        {
            _repoLeilao = repoLeilao;
            _repoInteressada = repoInteressada;
        }

        public IActionResult Index()
        {
            var usuarioLogado = this.HttpContext.Session.Get<Usuario>("usuarioLogado");
            var interessada = _repoInteressada
                .BuscarPorId(usuarioLogado.Interessada.Id);
            var model = new DashboardInteressadaViewModel
            {
                MinhasOfertas = interessada.Lances,
                LeiloesFavoritos = interessada.Favoritos.Select(f => f.LeilaoFavorito)
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult OfertaLance(LanceViewModel model)
        {
            if (ModelState.IsValid)
            {
                Leilao leilao = _repoLeilao.BuscarPorId(model.LeilaoId);
                Interessada interessada = _repoInteressada.BuscarPorId(model.UsuarioLogadoId);
                leilao.RecebeLance(interessada, model.Valor);
                _repoLeilao.Alterar(leilao); //?
                return Ok();
            }
            return BadRequest();
        }

        [HttpPost]
        public IActionResult SeguirLeilao(FavoritoViewModel model)
        {
            var leilao = _repoLeilao.BuscarPorId(model.IdLeilao);
            if (leilao != null)
            {
                var favorito = new Favorito
                {
                    IdLeilao = model.IdLeilao,
                    IdInteressada = model.IdInteressada
                };
                leilao.Seguidores.Add(favorito);
                _repoLeilao.Alterar(leilao);
                return Ok();
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult AbandonarLeilao(FavoritoViewModel model)
        {
            var leilao = _repoLeilao.BuscarPorId(model.IdLeilao);
            if (leilao != null)
            {
                var favorito = leilao.Seguidores
                    .FirstOrDefault(s =>
                        s.IdLeilao == model.IdLeilao &&
                        s.IdInteressada == model.IdInteressada);
                leilao.Seguidores.Remove(favorito);
                _repoLeilao.Alterar(leilao);
                return Ok();
            }
            return NotFound();
        }

    }
}

SeleniumTests/Alura.LeilaoOnline.WebApp/Controllers/LeiloesController.cs
using Microsoft.AspNetCore.Mvc;
using Alura.LeilaoOnline.Core;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.WebApp.Dados;
using System.Collections.Generic;
using System.Linq;
using Alura.LeilaoOnline.WebApp.Extensions;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Alura.LeilaoOnline.WebApp.Filtros;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    [AutorizacaoFilterAttribute]
    public class LeiloesController : Controller
    {
        private readonly IRepositorio<Leilao> _repo;
        private readonly IHostingEnvironment _env;

        private string TentaGravarImagemDestaqueERetornaSeuNome(IFormFile upload)
        {
            if (upload != null)
            {
                var nomeArquivoServidor = Path.Combine(
                    _env.WebRootPath,
                    "images",
                    upload.FileName);
                using (var stream = new FileStream(nomeArquivoServidor, FileMode.OpenOrCreate))
                {
                    upload.CopyTo(stream);
                }
            }
            return $"/images/{upload.FileName}";
        }

        public LeiloesController(IRepositorio<Leilao> repositorio, IHostingEnvironment environment)
        {
            _repo = repositorio;
            _env = environment;
        }

        public IActionResult Index()
        {
            var leiloes = _repo.Todos.Select(l => l.ToViewModel());
            return View(leiloes);
        }

        [HttpGet]
        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Novo(LeilaoViewModel model)
        {
            if (ModelState.IsValid)
            {
                //gravar arquivo com a imagem definida
                model.Imagem = this.TentaGravarImagemDestaqueERetornaSeuNome(model.ArquivoImagem);
                var novoLeilao = model.ToModel();
                _repo.Incluir(novoLeilao);
                return RedirectToAction("Index");
            }
            return View("Novo", model);
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            //var leilao = _repo.BuscarPorId(id);
            var leilao = new LeilaoViewModel();
            if(leilao != null)
            {
                //_repo.Excluir(leilao);
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        //[HttpGet]
        //public IActionResult Visualiza(int id)
        //{
        //    var leilao = _repo.BuscarPorId(id);
        //    if(leilao != null) {
        //      return View(leilao);
        //    }
        //    return NotFound();
        //}
    }
}

SeleniumTests/Alura.LeilaoOnline.WebApp/Views/Interessadas/Index.cshtml
@model DashboardInteressadaViewModel
@{
    ViewData["Title"] = "Dashboard";
}

<div class="container">
    <div class="row">
        <div class="col s12 m8">
            <div class="card minhas-ofertas">
                <div class="card-content">
                    <span class="card-title">Minhas Ofertas</span>
                    <table class="striped">
                        <thead>
                            <tr>
                                <th>Leilão</th>
                                <th>Valor</th>
                                <th>Situação</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var lance in Model.MinhasOfertas)
                            {
                                <tr>
                                    <td>@lance.Leilao.Titulo</td>
                                    <td>@lance.Valor</td>
                                    <td>Atual</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Leilões Favoritos</span>
                    <ul class="collection">
                        @foreach (var favorito in Model.LeiloesFavoritos)
                        {
                            <li class="collection-item">
                                @favorito.Titulo
                                <a href="#!" class="secondary-content">
                                    <i class="material-icons">close</i>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

SeleniumTests/Alura.LeilaoOnline.WebApp/Views/Leiloes/Index.cshtml
@model IEnumerable<Alura.LeilaoOnline.WebApp.Models.LeilaoViewModel>

@{
    ViewData["Title"] = "Index";
}

@*<div class="fixed-action-btn">
    <a asp-controller="Leiloes" asp-action="Novo" class="btn-floating btn-large waves-effect waves-light">
        <i class="material-icons">add</i>
    </a>
</div>*@

<!-- Modal Structure -->
<div id="modalConfirmaDelLeilao" class="modal">
    <div class="modal-content">
        <h4>Confirmação</h4>
        <p>Tem certeza que deseja excluir o leilão?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="modal-close btn-flat">Não</a>
        <form asp-action="Remove" asp-controller="Leiloes">
            <input type="hidden" name="id" value="2" class="inline" />
            <button class="modal-close waves-effect waves-green btn-flat">Sim</button>
        </form>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col s12 m8">
            <!-- Tabela com os leilões cadastrados -->
            <div class="card">
                <div class="card-content">
                    <h4 class="card-title">
                        Leilões cadastrados no sistema
                        <a asp-action="Novo" asp-controller="Leiloes" class="right red btn-small btn-floating waves-effect waves-light">
                            <i class="material-icons">add</i>
                        </a>

                    </h4>
                    <table class="highlight responsive-table">
                        <thead>
                            <tr>
                                <th>Descrição</th>
                                <th>Valor Inicial</th>
                                <th>Categoria</th>
                                <th>Estado Atual</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var leilao in Model)
                            {
                                <tr>
                                    <td>@leilao.Titulo</td>
                                    <td>@leilao.ValorInicial</td>
                                    <td>@leilao.Categoria</td>
                                    <td>@leilao.Estado</td>
                                    <td>
                                        <a class="modal-trigger black-text" href="#modalConfirmaDelLeilao"><i class="material-icons">close</i></a>
                                    </td>
                                </tr>
                            }
                            @*<tr>
                                <td>Réplica de pintura</td>
                                <td>1.000,00</td>
                                <td>Arte e Pintura</td>
                                <td>Não iniciado</td>
                                <td>
                                    <a class="black-text" asp-controller="Leiloes" asp-action="Remove" asp-route-id="2"><i class="material-icons">close</i></a>
                                </td>
                            </tr>
                            <tr>
                                <td>Réplica de pintura</td>
                                <td>1.000,00</td>
                                <td>Arte e Pintura</td>
                                <td>Não iniciado</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Réplica de pintura</td>
                                <td>1.000,00</td>
                                <td>Arte e Pintura</td>
                                <td>Não iniciado</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Réplica de pintura</td>
                                <td>1.000,00</td>
                                <td>Arte e Pintura</td>
                                <td>Não iniciado</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Réplica de pintura</td>
                                <td>1.000,00</td>
                                <td>Arte e Pintura</td>
                                <td>Não iniciado</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Réplica de pintura</td>
                                <td>1.000,00</td>
                                <td>Arte e Pintura</td>
                                <td>Não iniciado</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Réplica de pintura</td>
                                <td>1.000,00</td>
                                <td>Arte e Pintura</td>
                                <td>Não iniciado</td>
                                <td></td>
                            </tr>*@
                        </tbody>
                    </table>
                </div>
                <!--card.content>table-->
                <div class="card-action">
                    @*<span>Mostrando 1 de 10 de 67 registros.</span>*@
                    <ul class="pagination right-align">
                        <li class="disabled">
                            <a href="#!" class="grey-text text-lighten-2">
                                <i class="material-icons">chevron_left</i>
                            </a>
                        </li>
                        <li class="active waves-effect red">
                            <a href="#!" class="white-text">1</a>
                        </li>
                        <li class="waves-effect">
                            <a href="#!" class="grey-text">2</a>
                        </li>
                        <li class="waves-effect">
                            <a href="#!" class="grey-text">3</a>
                        </li>
                        <li class="waves-effect">
                            <a href="#!" class="grey-text">
                                <i class="material-icons">chevron_right</i>
                            </a>
                        </li>
                    </ul>
                    <!--ul.pagination-->
                </div>
            </div>
            <!--div.card-->
        </div>
        <div class="col s12 m4">
            <!-- Filtro rápido de leilões -->
            <div class="card teal white-text">
                <div class="card-content">
                    <span class="card-title">
                        <i class="material-icons left">search</i>
                        Filtro
                    </span>
                    <ul class="collection with-header">
                        <li class="collection-item collection-header teal darken-2 white-text">Categoria</li>
                        <li class="collection-item teal white-text"><a href="#!">Automóveis</a></li>
                        <li class="collection-item teal white-text"><a href="#!">Arte e Pintura</a></li>
                        <li class="collection-item teal white-text"><a href="#!">Itens de Colecionador</a></li>
                    </ul>
                </div>
                <!--div.card-content-->
            </div>
            <!--div.card filtro-->
        </div>
    </div>
</div>