ByteBank/Alura.ByteBank.WebApp/Controllers/AgenciaController.cs
using Alura.ByteBank.Aplicacao.AplicacaoServico;
using Alura.ByteBank.Aplicacao.DTO;
using Alura.ByteBank.Aplicacao.Interfaces;
using Alura.ByteBank.Dados.Repositorio;
using Alura.ByteBank.Dominio.Entidades;
using Alura.ByteBank.Dominio.Interfaces.Repositorios;
using Alura.ByteBank.Dominio.Interfaces.Servicos;
using Alura.ByteBank.Dominio.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Alura.ByteBank.WebApp.Controllers
{
    public class AgenciaController : Controller
    {
        // GET: AgenciaController    
        private readonly IAgenciaRepositorio _repositorio;
        private readonly IAgenciaServico _servico;
        private readonly IAgenciaServicoApp agenciaServicoApp;

        public AgenciaController(IAgenciaRepositorio repositorio)
        {
            _repositorio = repositorio;
            _servico = new AgenciaServico(_repositorio);
            agenciaServicoApp = new AgenciaServicoApp(_servico);
        }

        [Authorize]
        public ActionResult Index()
        {
            return View(agenciaServicoApp.ObterTodos());
        }

        // GET: AgenciaController/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var agencia = agenciaServicoApp.ObterPorId(id);
            return View(agencia);
        }

        // GET: AgenciaController/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: AgenciaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind("Id,Identificador,Numero,Nome,Endereco")] AgenciaDTO agencia)
        {
            try
            {
                agenciaServicoApp.Adicionar(agencia);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(agencia);
            }
        }

        // GET: AgenciaController/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var agencia = agenciaServicoApp.ObterPorId(id);
            if (agencia == null)
            {
                return NotFound();
            }
            return View(agencia);
        }

        // POST: AgenciaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, [Bind("Id,Identificador,Numero,Nome,Endereco")] AgenciaDTO agencia)
        {

            if (id != agencia.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    agenciaServicoApp.Atualizar(id, agencia);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AgenciaExists(agencia.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(agencia);
        }

        // GET: AgenciaController/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {

            var agencia = agenciaServicoApp.ObterPorId(id);

            if (agencia == null)
            {
                return NotFound();
            }

            agenciaServicoApp.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: AgenciaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            var agencia = agenciaServicoApp.ObterPorId(id);
            agenciaServicoApp.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        private bool AgenciaExists(int id)
        {
            var agencia = agenciaServicoApp.ObterPorId(id);
            return agencia == null ? true : false;
        }
    }
}

ByteBank/Alura.ByteBank.WebApp/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Alura.ByteBank.Dados.Contexto;
using Alura.ByteBank.Dominio.Entidades;
using Alura.ByteBank.Dados.Repositorio;
using Microsoft.AspNetCore.Authorization;
using Alura.ByteBank.Aplicacao.AplicacaoServico;
using Alura.ByteBank.Dominio.Interfaces.Servicos;
using Alura.ByteBank.Dominio.Interfaces.Repositorios;
using Alura.ByteBank.Dominio.Services;
using Alura.ByteBank.Aplicacao.DTO;

namespace Alura.ByteBank.WebApp.Controllers
{

    public class ClientesController : Controller
    {

        private readonly IClienteRepositorio _repositorio;
        private readonly IClienteServico _servico;
        private readonly ClienteServicoApp clienteServicoApp;
        public ClientesController(IClienteRepositorio repositorio)
        {
            _repositorio = repositorio;
            _servico = new ClienteServico(_repositorio);
            clienteServicoApp = new ClienteServicoApp(_servico);
        }

        // GET: Clientes
        [Authorize]
        public IActionResult Index()
        {
            return View(clienteServicoApp.ObterTodos());
        }

        // GET: Clientes/Details/5
        [Authorize]
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = clienteServicoApp.ObterPorId(id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,Identificador,CPF,Nome,Profissao")] ClienteDTO cliente)
        {
            if (ModelState.IsValid)
            {
                clienteServicoApp.Adicionar(cliente);
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = clienteServicoApp.ObterPorId(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, [Bind("Id,Identificador,CPF,Nome,Profissao")] ClienteDTO cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    clienteServicoApp.Atualizar(id, cliente);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = clienteServicoApp.ObterPorId(id);

            if (cliente == null)
            {
                return NotFound();
            }

            clienteServicoApp.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            var cliente = clienteServicoApp.ObterPorId(id);
            clienteServicoApp.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            var cliente = clienteServicoApp.ObterPorId(id);
            return cliente == null ? true : false;
        }
    }
}

ByteBank/Alura.ByteBank.WebApp/Controllers/ContaCorrentesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Alura.ByteBank.Dados.Contexto;
using Alura.ByteBank.Dominio.Entidades;
using Alura.ByteBank.Dados.Repositorio;
using Microsoft.AspNetCore.Authorization;
using Alura.ByteBank.Dominio.Interfaces.Repositorios;
using Alura.ByteBank.Dominio.Interfaces.Servicos;
using Alura.ByteBank.Aplicacao.AplicacaoServico;
using Alura.ByteBank.Dominio.Services;
using Alura.ByteBank.Aplicacao.DTO;

namespace Alura.ByteBank.WebApp.Controllers
{

    public class ContaCorrentesController : Controller
    {
        private readonly IContaCorrenteRepositorio _repositorio;
        private readonly IContaCorrenteServico _servico;
        private readonly IClienteServico _servicoCliente;
        private readonly IAgenciaServico _servicoAgencia;
        private readonly ContaCorrenteServicoApp contaCorrenteServicoApp;

        public ContaCorrentesController(IContaCorrenteRepositorio repositorio,
                                        IClienteRepositorio repositorioCliente,
                                        IAgenciaRepositorio repositorioAgencia)
        {
            _repositorio = repositorio;
            _servico = new ContaCorrenteServico(_repositorio);
            _servicoCliente = new ClienteServico(repositorioCliente);
            _servicoAgencia = new AgenciaServico(repositorioAgencia); ;
            contaCorrenteServicoApp = new ContaCorrenteServicoApp(_servico, _servicoAgencia, _servicoCliente);
        }
        [Authorize]
        // GET: ContaCorrentes
        public ActionResult Index()
        {
            return View(contaCorrenteServicoApp.ObterTodos());
        }

        [Authorize]
        // GET: ContaCorrentes/Details/5
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaCorrente = contaCorrenteServicoApp.ObterPorId(id);

            if (contaCorrente == null)
            {
                return NotFound();
            }

            return View(contaCorrente);
        }

        [Authorize]
        // GET: ContaCorrentes/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClienteId,AgenciaId,Numero,Identificador,Saldo,PixConta")] ContaCorrenteDTO contaCorrente)
        {
            if (ModelState.IsValid)
            {
                contaCorrenteServicoApp.Adicionar(contaCorrente);
                return RedirectToAction(nameof(Index));
            }
            return View(contaCorrente);
        }

        // GET: ContaCorrentes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaCorrente = contaCorrenteServicoApp.ObterPorId(id); ;
            if (contaCorrente == null)
            {
                return NotFound();
            }
            return View(contaCorrente);
        }

        // POST: ContaCorrentes/Edit/5
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("Id,ClienteId,AgenciaId,Numero,Identificador,Saldo,PixConta")] ContaCorrenteDTO contaCorrente)
        {
            if (id != contaCorrente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    contaCorrenteServicoApp.Atualizar(id, contaCorrente);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContaCorrenteExists(contaCorrente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contaCorrente);
        }

        // GET: ContaCorrentes/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaCorrente = contaCorrenteServicoApp.ObterPorId(id);
            if (contaCorrente == null)
            {
                return NotFound();
            }

            contaCorrenteServicoApp.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: ContaCorrentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var contaCorrente = contaCorrenteServicoApp.ObterPorId(id);
            contaCorrenteServicoApp.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ContaCorrenteExists(int id)
        {
            var contaCorrente = contaCorrenteServicoApp.ObterPorId(id);
            return contaCorrente == null ? true : false;
        }
    }
}

ByteBank/Alura.ByteBank.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alura.ByteBank.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ByteBank-WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" id="home" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" id="agencia" asp-controller="Agencia" asp-action="Index">Agência</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" id="clientes" asp-controller="Clientes" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" id="contacorrente" asp-controller="ContaCorrentes" asp-action="Index">Conta-Corrente</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="UsuarioApps" asp-action="Logout">Logout</a>*@
                            <form method="post" asp-controller="UsuarioApps" asp-action="Logout">
                                <input class="btn btn-link text-white" type="submit" value="Logout | @HttpContextAccessor.HttpContext.Session.GetString("user")" />
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark">
        <div class="container">
            &copy; 2021 - Alura.ByteBank.WebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ByteBank/Alura.ByteBank.WebApp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alura.ByteBank.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="UsuarioApps" asp-action="Login">ByteBank-WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="UsuarioApps" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark">
        <div class="container">
            &copy; 2021 - Alura.ByteBank.WebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ByteBank/Alura.ByteBank.WebApp/Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alura.ByteBank.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ByteBank-WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="PrincipalHome">Home</a>
                        </li>                     
                    </ul>
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="UsuarioApps" asp-action="Login">Login</a>
                            
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark">
        <div class="container">
            &copy; 2021 - Alura.ByteBank.WebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>